### PR TITLE
feat(router): Get the annotations from the deployment object instead of RC

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by krancour** [comment]
@kmala does this need to be coordinated with a deis/charts change?

**Comment by kmala** [comment]
deis/charts already started using deployments https://github.com/deis/charts/pull/316

**Comment by krancour** [comment]
@kmala that is interesting... I am wondering how it is that everything hasn't broken if the chart uses a deployment for router while router (before this PR) looks for annotations upon its own _rc_.

**Comment by kmala** [comment]
because we still have deprecated RC's still laying around as part of the charts

**Comment by krancour** [comment]
Got it.

**Comment by sstarcher** [comment]
I learned about the requirement of the rc still existing in v.2.3 the hard way.

**Pull request merged**
