### PR TITLE
chore(manifests): remove superfluous app label on rc; add heritage

### PR DESCRIPTION
**Pull request by krancour**

### CODE REVIEW

**Comment by bacongobbler** [comment]
I know that we use the app label still, but I agree that it is superflous since the `name` metadata is the exact same thing, so LGTM.

**Comment by technosophos** [comment]
Please put the `app` label back on. That label is used by some k8s admin tools, and we're trying to make sure we are compatible.

http://kubernetes.io/v1.1/docs/user-guide/walkthrough/k8s201.html

**Comment by technosophos** [comment]
@krancour pointed out offline that RCs do not have the app label. Only pods and pod templates.

**Comment by krancour** [comment]
Thanks @technosophos

**Pull request merged**
