### PR TITLE
chore(Makefile): Enable immutable (git-based) Docker tag publishing

### LINKED ISSUE #145: Publish immutable artifact tags + canary version to Docker registries
We want to have the ability to have deis/charts reference a specific immutable image which will enable us better traceability on issues that come into various components.

What we've done with efforts in other repositories is publish a version:
- `git-[short sha]` that will never be overwritten
- `canary` that will move to reference the latest version available of a component

Examples of the easiest way to roll this change out can be seen in deis/workflow#487, deis/builder#246, and deis/workflow-manager#11

### PR DESCRIPTION
**Pull request by krancour**
Fixes #145

### CODE REVIEW

**Comment by sgoings** [comment]
Thanks @krancour!

**Comment by krancour** [comment]
I made some edits cause of a goof.  Should be better now.

**Comment by sgoings** [comment]
Don't forget you'll also have to make an update to deis/charts like: https://github.com/deis/charts/pull/159

**Comment by krancour** [comment]
Yerp.  Thanks for the reminder!

**Comment by arschles** [comment]
LGTM3

**Pull request merged**
