### PR TITLE
chore(router): prefix annotations with deis.com/

### PR DESCRIPTION
**Pull request by krancour**
Suggested by @technosophos

### CODE REVIEW

**Comment by krancour** [comment]
Merge conflicts fixed.

**Comment by helgi** [comment]
We want `.com` instead of `.io` ?

**Comment by bacongobbler** [comment]
I'm +1 on using .io since that's the open-sourcey side of Deis where .com is the commercial support side. Makes more sense to differentiate between the two (then if we have commercial apps in the future we could use deis.com annotations)

**Comment by krancour** [comment]
I defer to @technosophos on this.  It was his suggestion.

**Comment by helgi** [comment]
cc @slack

**Comment by krancour** [comment]
fwiw, I'd throw my vote to `deis.io` too.

**Comment by slack** [comment]
I don't mind `.io`

**Comment by krancour** [comment]
Switched to `.io`

**Comment by krancour** [comment]
Going to treat the LGTMs as if they still stand and proceed with merging after CI passes, unless anyone speaks up between now and then.

**Pull request merged**
